### ISSUE TITLE
Cycle through RPCs if initialisation fails

### ISSUE THREAD

**Issue by peetzweg** [scio-labs/use-inkathon#73] opened 2024-05-03 15:38 UTC
As of now rpc1 of Pop Network seems to be broken/down temporarily. The chains config for pop has 3 rpc configured. However, my dapp using Pop network is broken as it just tries to connect to the first rpc in the rpc array. 

It would be great if it would cycle through the rpcs in the chains config if the current one fails.

As of now I'm not aware how to make use-inkathon use another rpc than the first one in the hardcoded SubstrateChain object.

**Comment by wottpal** [comment] 2024-05-03 16:16
I would say this is most probably a duplicate of #5. Let's close it here and continue discussion there (tagged you).

**Closed by wottpal** 2024-05-03 16:16 UTC
